"""
Personalab -- Synthetic identity infrastructure with pluggable generation backends.

Public API: create characters, generate ideas, images, and videos;
convert user prompts to the project's prompt format.

Subpackages: config, llm, prompts, schemas, tools, identity, orchestration, generation, observability.
"""

from personalab.schemas import (
    Character,
    ScenarioDetails,
    ContentPlanScenario,
    ContentPlan,
    ImagePrompt,
    VideoPrompt,
    ImageGenMeta,
    VideoGenMeta,
    get_llm_schemas,
)
from personalab.config import load_config, ProjectConfig
from personalab.llm import (
    LLMClient,
    TextPart,
    BytesPart,
    ContentPart,
    LLMTextResponse,
    LLMImageResponse,
    LLMVideoResponse,
    GeminiAdapter,
    RoutingClient,
    create_client,
)
from personalab.prompts import PromptBuilder, PassThroughPromptBuilder, GeminiPromptBuilder
from personalab.generation import IdeaGenerator, ImageGenerator, VideoGenerator
from personalab.tools import apply_instagram_realism, load_realism_config, IGRealismConfig
from personalab.identity import (
    AnchorPack,
    load_anchor_pack,
    select_anchor,
    IdentityPolicy,
    Decision,
    IdentityEvaluator,
    StubEvaluator,
    CompositeEvaluator,
    DriftTracker,
    EvaluationResult,
    EmbeddingScore,
    EmbeddingTemporalStats,
    GeometricTemporalStats,
    LandmarkScore,
    CandidateResult,
    FrameEvaluationResult,
    VideoEvaluationResult,
    FrameExtractor,
    ExtractedFrame,
    VideoIdentityEvaluator,
    StubVideoEvaluator,
    DriftRecord,
    DriftSummary,
    build_evaluator,
)
from personalab.quality import (
    FrameSharpness,
    IlluminationCheck,
    PostProcessingAdvice,
    VideoQualityResult,
    SharpnessEvaluator,
    IlluminationEvaluator,
    VideoQualityEvaluator,
    PostProcessingGate,
)
from personalab.orchestration import (
    RegistryWriter,
    GenerationOrchestrator,
    GenerationAttempt,
    OrchestrationResult,
    VideoOrchestrator,
    VideoGenerationAttempt,
    VideoOrchestrationResult,
)
from personalab.observability import GenerationMetricsLogger
from personalab.runtime import (
    JobSpec,
    JobResult,
    compute_config_hash,
    Runner,
    SyncRunner,
    AsyncRunner,
    ProviderSemaphore,
    RateLimiter,
    EvaluationPool,
    RetryPolicy,
)

__all__ = [
    "Character",
    "ScenarioDetails",
    "ContentPlanScenario",
    "ContentPlan",
    "ImagePrompt",
    "VideoPrompt",
    "ImageGenMeta",
    "VideoGenMeta",
    "get_llm_schemas",
    "load_config",
    "ProjectConfig",
    "LLMClient",
    "TextPart",
    "BytesPart",
    "ContentPart",
    "LLMTextResponse",
    "LLMImageResponse",
    "LLMVideoResponse",
    "GeminiAdapter",
    "RoutingClient",
    "create_client",
    "PromptBuilder",
    "PassThroughPromptBuilder",
    "GeminiPromptBuilder",
    "IdeaGenerator",
    "ImageGenerator",
    "VideoGenerator",
    "apply_instagram_realism",
    "load_realism_config",
    "IGRealismConfig",
    "AnchorPack",
    "load_anchor_pack",
    "select_anchor",
    "IdentityPolicy",
    "Decision",
    "IdentityEvaluator",
    "StubEvaluator",
    "CompositeEvaluator",
    "DriftTracker",
    "EvaluationResult",
    "EmbeddingScore",
    "EmbeddingTemporalStats",
    "GeometricTemporalStats",
    "LandmarkScore",
    "CandidateResult",
    "FrameEvaluationResult",
    "VideoEvaluationResult",
    "FrameExtractor",
    "ExtractedFrame",
    "VideoIdentityEvaluator",
    "StubVideoEvaluator",
    "DriftRecord",
    "DriftSummary",
    "build_evaluator",
    "FrameSharpness",
    "IlluminationCheck",
    "PostProcessingAdvice",
    "VideoQualityResult",
    "SharpnessEvaluator",
    "IlluminationEvaluator",
    "VideoQualityEvaluator",
    "PostProcessingGate",
    "RegistryWriter",
    "GenerationOrchestrator",
    "GenerationAttempt",
    "OrchestrationResult",
    "VideoOrchestrator",
    "VideoGenerationAttempt",
    "VideoOrchestrationResult",
    "GenerationMetricsLogger",
    "JobSpec",
    "JobResult",
    "compute_config_hash",
    "Runner",
    "SyncRunner",
    "AsyncRunner",
    "ProviderSemaphore",
    "RateLimiter",
    "EvaluationPool",
    "RetryPolicy",
]

__version__ = "0.1.0"
